version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sergh2508Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: AddIntsPackage
  version: "1.0"
  gitServerName: srcCtrl_shared_AzRepos_Arti
  gitUrl: https://dev.azure.com/ArtiKhare/AddIntsPackage/_git
  gitUsername: ArtiKhare
  gitBranch: master
- name: CurrentDatePackage
  version: sdjfhsjfhsdl
  gitServerName: src_shared_GithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: testversion
services:
- serviceName: project.sergh2508.integrations:azrepoPackage
  packages:
  - name: Sergh2508Project
    version: "1.0"
  - name: AddIntsPackage
    version: "1.0"
  - name: CurrentDatePackage
    version: sdjfhsjfhsdl
- serviceName: AddIntsPackage:addIntsFS
  packages:
  - name: AddIntsPackage
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2080
